#
# Copyright 2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

demo-app-with-storage:
  # 示例项目的开关配置
  feature-control:
    # 数据库开关(请求日志、苏标附件文件信息会写入数据库)
    ## 可以同时启用多个
    database:
      ## 仅仅打了个日志用来调试
      logging:
        enabled: true
      ## 存储到 Clickhouse 中
      clickhouse:
        enabled: ${FEATURE_CONTROL_DATABASE_CLICKHOUSE_ENABLED:false}
      ## 存储到 MySQL 中
      mysql:
        enabled: ${FEATURE_CONTROL_DATABASE_MYSQL_ENABLED:true}
      ## 存储到 Postgres 中
      postgres:
        enabled: ${FEATURE_CONTROL_DATABASE_POSTGRES_ENABLED:false}
    # OSS(对象存储服务)开关(苏标附件文件会上传到启用的OSS中)
    ## 可以同时启用多个
    oss:
      ## 仅仅打了个附件文件信息日志用来调试
      logging:
        enabled: true
      ## 文件会存储到Minio中
      minio:
        enabled: ${FEATURE_CONTROL_OSS_MINIO_ENABLED:true}
  minio:
    endpoint: ${MINIO_ENDPOINT:http://192.168.4.238:9000}
    access-key: ${MINIO_ACCESS_KEY:IMesOv1gMCvyQECUUDSo}
    secret-key: ${MINIO_SECRET_KEY:zI6O2JlRwlqNYpGD9c7NLTjuZnZWK2HNR71PHC4I}
  # 示例性的附件服务器配置
  attachment-server:
    # 附件服务器的IP 应该是一个公网IP(设备能访问的IP)
    server-ip: ${ATTACHMENT_SERVER_IP:192.168.4.238}
    # 用来存放附件文件的临时路径
    temporary-path: /tmp/jt-808/attachment
    # 将本地文件上传到远程存储后，是否保留本地文件
    retain-local-temporary-file: false
    # 远程存储的 bucket 名称(对应上面 minio 的 bucketName)
    # 项目启动时会自动创建(为简化示例，会自动将 bucket 改为可匿名访问)
    remote-storage-bucket-name: jt-attachment
    file-preview-base-url: ${demo-app-with-storage.minio.endpoint}/${demo-app-with-storage.attachment-server.remote-storage-bucket-name}

server:
  port: 8888

spring:
  main:
    # [非阻塞]环境下，显式指定 Reactive(不配置也可以,默认就是Netty)
    web-application-type: reactive
  web:
    resources:
      static-locations:
        - classpath:/static/quickstart-ui/
  r2dbc:
    mybatis:
      routing:
        enabled: true
        definitions:
          - name: trace-log-mysql
            as-default: true
            # r2dbc-url: r2dbc:mysql://[username[:password]@]hostname[:port]/[database][?property1=value1&...]
            r2dbc-url: ${MYSQL_R2DBC_URL:r2dbc:mysql://localhost:3307/jt_808}
            username: ${MYSQL_R2DBC_USERNAME:root}
            password: ${MYSQL_R2DBC_PASSWORD:ddm@126.com}
            pool:
              max-idle-time: PT5M
              validation-query: SELECT 1
              initial-size: 16
              max-size: 16
              acquire-retry: 3
              validation-depth: REMOTE
              max-create-connection-time: PT10S
          - name: trace-log-postgres
            as-default: false
            r2dbc-url: ${POSTGRES_R2DBC_URL:r2dbc:postgres://localhost:5432/jt_808}
            username: ${POSTGRES_R2DBC_USERNAME:jt}
            password: ${POSTGRES_R2DBC_PASSWORD:postgres}
            pool:
              max-idle-time: PT5M
              validation-query: SELECT 1
              initial-size: 16
              max-size: 16
              acquire-retry: 3
              validation-depth: REMOTE
              max-create-connection-time: PT10S
          - name: trace-log-clickhouse
            as-default: false
            r2dbc-url: ${CLICKHOUSE_R2DBC_URL:r2dbc:clickhouse://localhost:8123/jt_808}
            username: ${CLICKHOUSE_R2DBC_USERNAME:jt}
            password: ${CLICKHOUSE_R2DBC_PASSWORD:clickhouse}
            pool:
              max-idle-time: PT5M
              validation-query: SELECT 1
              initial-size: 16
              max-size: 16
              acquire-retry: 3
              validation-depth: REMOTE
              max-create-connection-time: PT10S

r2dbc:
  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

########################################################
### xtream-codec-server-reactive 配置####################
########################################################
jt808-server:
  # false: 不会进行任何自动配置
  enabled: true
  features:
    dashboard:
      enabled: true
      # 示例项目有自己的首页 所以不用重定向到dashboard首页
      redirect-root-to-base-path: false
  ## 指令服务器
  instruction-server:
    # TCP 服务配置(指令服务器)
    tcp-server:
      # 是否启动 TCP 服务
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # TCP 服务端口
      port: 3927
      max-instruction-frame-length: 2048
    # UDP 服务配置(指令服务器)
    udp-server:
      # 是否启动 UDP 服务
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # UDP 服务端口
      port: 3721
  ## 附件服务器
  attachment-server:
    # TCP 服务配置(附件服务器)
    tcp-server:
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # TCP 服务端口
      port: 3824
    # UDP 服务配置(附件服务器)
    udp-server:
      enabled: true
      # 绑定所有网卡
      host: 0.0.0.0
      # UDP 服务端口
      port: 3618

logging:
  level:
    root: info
    io.netty.handler.logging.LoggingHandler: debug
